describe('install concurrency module', function()
  local a = require('nvim-treesitter.async')
  local M = require('nvim-treesitter.install.concurrency')

  before_each(function()
    M._reset()
  end)

  after_each(function()
    M._reset()
  end)

  describe('lock/is_installing', function()
    it('reports not installing by default', function()
      assert.is_false(M.is_installing('lua'))
    end)

    it('reports installing after lock', function()
      M.lock('lua')
      assert.is_true(M.is_installing('lua'))
    end)

    it('reports not installing after unlock', function()
      M.lock('lua')
      M.unlock('lua')
      assert.is_false(M.is_installing('lua'))
    end)
  end)

  describe('wait_unlock', function()
    it('returns true immediately when not installing', function()
      local task = a.arun(function()
        return M.wait_unlock('lua', 1000)
      end)
      local ok, released = task:pwait(5000)
      assert.is_true(ok)
      assert.is_true(released)
    end)

    it('waits until the lock is released', function()
      M.lock('c')
      local task = a.arun(function()
        return M.wait_unlock('c', 5000)
      end)
      vim.defer_fn(function()
        M.unlock('c')
      end, 300)
      local ok, released = task:pwait(5000)
      assert.is_true(ok)
      assert.is_true(released)
    end)

    it('returns false on timeout while locked', function()
      M.lock('rust')
      local task = a.arun(function()
        return M.wait_unlock('rust', 300)
      end)
      local ok, released = task:pwait(5000)
      assert.is_true(ok)
      assert.is_false(released)
    end)
  end)
end)
