describe('install error handling', function()
  local errors = require('nvim-treesitter.install.errors')
  local validate = require('nvim-treesitter.install.validate')
  local log = require('nvim-treesitter.log')
  local install_mod = require('nvim-treesitter.install.install')
  local concurrency = require('nvim-treesitter.install.concurrency')
  local a = require('nvim-treesitter.async')

  before_each(function()
    log._reset()
    concurrency._reset()
  end)

  after_each(function()
    concurrency._reset()
  end)

  describe('InstallError', function()
    it('creates an error with stage, lang, message, and cause', function()
      local err = errors.new('download', 'php', 'curl request failed', 'HTTP 404')
      assert.are.equal('download', err.stage)
      assert.are.equal('php', err.lang)
      assert.are.equal('curl request failed', err.message)
      assert.are.equal('HTTP 404', err.cause)
    end)

    it('causes without cause', function()
      local err = errors.new('compile', 'rust', 'build failed')
      assert.is_nil(err.cause)
    end)

    describe('__tostring', function()
      it('includes stage and language', function()
        local err = errors.new('download', 'php', 'request failed', 'HTTP 404')
        local s = tostring(err)
        assert.is_true(s:find('Failed to download parser', 1, true) ~= nil)
        assert.is_true(s:find("'php'", 1, true) ~= nil)
        assert.is_true(s:find('HTTP 404', 1, true) ~= nil)
      end)

      it('omits cause section when nil', function()
        local err = errors.new('validate', 'go', 'not found')
        local s = tostring(err)
        assert.is_true(s:find('Failed to validate parser', 1, true) ~= nil)
        assert.is_nil(s:find('Cause:', 1, true))
      end)

      it('shows cause when present', function()
        local err = errors.new('compile', 'ruby', 'exited with code 1', 'syntax error')
        local s = tostring(err)
        assert.is_true(s:find('Cause: syntax error', 1, true) ~= nil)
      end)
    end)

    describe('error() helper', function()
      it('logs via logger and returns InstallError', function()
        local logger = log.new('test/errors')
        local err = errors.error(logger, 'download', 'python', 'failed', 'timeout')
        assert.is_equal('download', err.stage)
        assert.is_equal('python', err.lang)
        local found = false
        for _, msg in ipairs(logger.messages) do
          if msg[1] == 'error' and msg[2] == 'test/errors' then
            found = true
          end
        end
        assert.is_true(found)
      end)

      it('returns an object with __tostring', function()
        local logger = log.new('test/errors2')
        local err = errors.error(logger, 'compile', 'lua', 'build failed')
        local s = tostring(err)
        assert.is_true(type(s) == 'string')
        assert.is_true(#s > 0)
      end)
    end)
  end)

  describe('validate module', function()
    describe('check_executable', function()
      it('returns nil for a known tool', function()
        assert.is_nil(validate.check_executable('ls'))
      end)

      it('returns error for missing tool', function()
        local err = validate.check_executable('this_tool_does_not_exist')
        assert.is_not_nil(err)
        assert.is_true(err:find('not found', 1, true) ~= nil)
      end)
    end)

    describe('check_tools', function()
      it('returns nil when all tools are available', function()
        assert.is_nil(validate.check_tools({ 'ls', 'cat' }))
      end)

      it('returns first missing tool error', function()
        local err = validate.check_tools({ 'ls', 'missing_tool_xyz' })
        assert.is_not_nil(err)
        assert.is_true(err:find('missing_tool_xyz', 1, true) ~= nil)
      end)
    end)

    describe('required_tools', function()
      it('includes tree-sitter for local checkouts', function()
        local repo = { path = '/some/local/path' }
        local tools = validate.required_tools(repo)
        assert.is_true(vim.list_contains(tools, 'tree-sitter'))
        assert.is_false(vim.list_contains(tools, 'curl'))
        assert.is_false(vim.list_contains(tools, 'tar'))
      end)

      it('includes curl and tar for remote download', function()
        local repo = { url = 'https://example.com/repo' }
        local tools = validate.required_tools(repo)
        assert.is_true(vim.list_contains(tools, 'tree-sitter'))
        assert.is_true(vim.list_contains(tools, 'curl'))
        assert.is_true(vim.list_contains(tools, 'tar'))
      end)

      it('includes curl and tar when repo is nil', function()
        local tools = validate.required_tools(nil)
        assert.is_true(vim.list_contains(tools, 'tree-sitter'))
        assert.is_true(vim.list_contains(tools, 'curl'))
        assert.is_true(vim.list_contains(tools, 'tar'))
      end)
    end)
  end)

  describe('install_lang error propagation', function()
    it('returns false and InstallError for unknown language', function()
      local results = {} ---@type {success: boolean?, err: InstallError?}
      local task = a.arun(function()
        results.success, results.err = install_mod.install_lang(
          'not_a_real_language', '/tmp/ts-cache-test', '/tmp/ts-install-test', false, false)
      end)
      local ok = task:pwait(10000)
      assert.is_true(ok)
      assert.is_false(results.success)
      assert.is_not_nil(results.err)
      assert.are.equal('validate', results.err.stage)
      assert.are.equal('not_a_real_language', results.err.lang)
    end)

    it('try_install_lang returns InstallError for unknown language', function()
      local results = {} ---@type {err: InstallError?}
      local logger = log.new('test/unknown')
      local task = a.arun(function()
        results.err = install_mod.try_install_lang(
          'not_a_real_language', '/tmp/ts-cache-test', '/tmp/ts-install-test', false, logger)
      end)
      local ok = task:pwait(10000)
      assert.is_true(ok)
      assert.is_not_nil(results.err)
      assert.are.equal('validate', results.err.stage)
      assert.are.equal('not_a_real_language', results.err.lang)
      local s = tostring(results.err)
      assert.is_true(s:find('no parser configuration', 1, true) ~= nil)
    end)
  end)
end)
