describe('install module', function()
  it('should have uninstall_lang function', function()
    local M = require('nvim-treesitter.install.install')
    assert.is_true(M.uninstall_lang ~= nil)
  end)

  it('should have try_install_lang function', function()
    local M = require('nvim-treesitter.install.install')
    assert.is_true(M.try_install_lang ~= nil)
  end)

  it('should have install_lang function', function()
    local M = require('nvim-treesitter.install.install')
    assert.is_true(M.install_lang ~= nil)
  end)

  it('should have get_package_path helper', function()
    local info = debug.getinfo(require('nvim-treesitter.install.install').try_install_lang)
    assert.is_true(info ~= nil)
  end)

  describe('public API with nil options', function()
    -- Regression: M.update used to index options.max_jobs unconditionally,
    -- crashing when called without an options table.
    it('install accepts nil options', function()
      local task = require('nvim-treesitter.install').install({ 'not_a_real_language' })
      local ok, success = task:pwait(10000)
      assert.is_true(ok)
      assert.is_true(success)
    end)

    it('update accepts nil options', function()
      local task = require('nvim-treesitter.install').update({ 'not_a_real_language' })
      local ok, success = task:pwait(10000)
      assert.is_true(ok)
      assert.is_true(success)
    end)

    it('uninstall accepts nil options', function()
      local task = require('nvim-treesitter.install').uninstall({ 'not_a_real_language' })
      local ok, success = task:pwait(10000)
      assert.is_true(ok)
      assert.is_true(success)
    end)
  end)
end)
